#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# Commitlint check
npx commitlint --edit "$1" > /dev/null 2>&1
RESULT=$?

if [ $RESULT -ne 0 ]; then
  echo ""
  echo "🚫 Commit message format is invalid!"
  echo "💡 Please follow the convention: <type>(scope): <subject>"
  echo "   Example: feat(bot): add new queue system"
  echo ""
  exit 1
fi
